#!/bin/bash
export REPOSITORY=github

dockerd --seccomp-profile unconfined --experimental &> /dev/null &

if docker compose --file /workspaces/$REPOSITORY/windows/windows.yaml images | grep --quiet "windows"; then
    docker compose --file /workspaces/$REPOSITORY/windows/windows.yaml start
else
    docker compose --file /workspaces/$REPOSITORY/windows/windows.yaml up
fi
